name       : python-soupsieve
version    : 2.4.1
release    : 13
source     :
    - https://github.com/facelessuser/soupsieve/archive/refs/tags/2.4.1.tar.gz : 66bb1420c8b02fab8ecac81994b961ab4dc72eddc032db06b45a2d3f105d6098
homepage   : https://facelessuser.github.io/soupsieve/
license    : MIT
component  : programming.python
summary    : A modern CSS selector implementation for BeautifulSoup
description: |
    Soup Sieve is a CSS selector library designed to be used with Beautiful Soup 4. It aims to provide selecting, matching, and filtering using modern CSS selectors. Soup Sieve currently provides selectors from the CSS level 1 specifications up through the latest CSS level 4 drafts and beyond (though some are not yet implemented).
builddeps  :
    - python-beautifulsoup4 # check (warning; circular)
    - python-build
    - python-hatchling
    - python-installer
    - python-pytest         # check
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
