name       : python-soupsieve
version    : 1.9.2
release    : 1
source     :
    - https://github.com/facelessuser/soupsieve/archive/1.9.2.tar.gz : 355ebfafc7495eee6a5f292574ec896d2d4ad214fa653d93f16792b1c4e4f8e8
license    : MIT
component  : programming.python
summary    : A modern CSS selector implementation for BeautifulSoup
description: |
    Soup Sieve is a CSS selector library designed to be used with Beautiful Soup 4. It aims to provide selecting, matching, and filtering using modern CSS selectors.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install