name       : python-soupsieve
version    : 2.3.2
release    : 12
source     :
    - https://github.com/facelessuser/soupsieve/archive/refs/tags/2.3.2.post1.tar.gz : 2f6a3926d6ee7e360654263b514c2fe850e2fecb48cee3e4a3d8afbcf059830f
homepage   : https://facelessuser.github.io/soupsieve/
license    : MIT
component  : programming.python
summary    : A modern CSS selector implementation for BeautifulSoup
description: |
    Soup Sieve is a CSS selector library designed to be used with Beautiful Soup 4. It aims to provide selecting, matching, and filtering using modern CSS selectors. Soup Sieve currently provides selectors from the CSS level 1 specifications up through the latest CSS level 4 drafts and beyond (though some are not yet implemented).
builddeps  :
    - python-beautifulsoup4 # check (warning; circular)
    - python-build
    - python-hatchling
    - python-installer
    - python-pytest         # check
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
